name: salt_code_test
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  cached_network_image: ^3.3.1
  equatable: ^2.0.5
  dio: ^5.3.3
  auto_route: ^8.1.3
  internet_connection_checker_plus: ^2.2.0
  skeletonizer: ^1.1.2+1
  flex_color_scheme: ^7.3.1
  another_flushbar: ^1.12.30
  google_fonts: ^6.1.0
  sqflite: ^2.3.3+1
  get_it: ^7.7.0
  flutter_bloc: ^8.1.5
  stream_transform: ^2.1.0
  bloc_concurrency: ^0.2.5
  shimmer: ^3.0.0
  intl: ^0.17.0
  logger: ^2.3.0
  webview_flutter: ^4.7.0
  utils:
    path: utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.3.0
  auto_route_generator: ^8.0.0
  mockito: ^5.4.2
  bloc_test: ^9.1.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
